


<div class="content-header" style="visibility: visible;">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td style="width: 50%;"><h3
						style="background-image: url(http://www.megaventory.com/favicon.ico);background-size:16px;"
						class="icon-head">Megaventory (version <?php echo Mv_Megaventory_Helper_Common::getExtensionVersion()?>)</h3></td>
			</tr>
		</tbody>
	</table>

</div>

<?php 
$indexURL = Mage::helper("adminhtml")->getUrl("megaventory/index/index");

$formAction = Mage::helper("adminhtml")->getUrl("megaventory/index/saveSettings");
$apikey = $this->getSettingValue('apikey');
$apiurl = $this->getSettingValue('apiurl');
$enabled = $this->getSettingValue('enabled');
$orderSyncrhonization = $this->getSettingValue('ordersynchronization');
if (empty($orderSyncrhonization))
	$orderSyncrhonization = '0';

$syncTimestamp = $this->getSettingValue('synctimestamp');

$connectivityOk = $this->connectivityOk();

$magentoInstallations = $this->getMagentoInstallations();
$magentoId = $this->getSettingValue('magentoid');

if ($connectivityOk !== true){
	$actionsDisabled = ' disabled ';
	$buttonOnClick = ' onclick="" ';
}
else{
	$actionsDisabled = '';
}
?>

<form action="<?php echo $formAction ?>" method="post"
	id="megaventory_settings_form">
	<table width="100%">
		<tr>
			<td width="50%" style="padding-right: 15px">
				<div>
					<input name="form_key" type="hidden"
						value="<?php echo $this->getFormKey() ?>">
				</div>
				<div class="entry-edit">
					<div class="entry-edit-head collapseable">
						<a id="megaventory_connectivity-head" href="#"
							onclick="Fieldset.toggleCollapse('megaventory_connectivity', ''); return false;"
							class="open">Connectivity</a>
					</div>
					<input id="megaventory_connectivity-state" type="hidden" value="1">
					<fieldset class="config collapseable" id="megaventory_connectivity"
						style="">
						<legend>Connectivity</legend>
						<table cellspacing="0" class="form-list">
							<tbody>
								<?php if(empty($syncTimestamp)){ 
									if (empty($apikey) || empty($apiurl)) {
								?>
								<tr id="row_megaventory_link">
									<td class="label" colspan="2">
										If you don't already have a Megaventory Account please <a href="http://megaventory.com/?getstarted=1" target="_blank">Click Here</a>
									</td>
								</tr>
								<?php 
									} 
								
								}?>
								<tr id="row_megaventory_connectivity_enabled">
									<td class="label"><label
										for="megaventory_connectivity_enabled-id"> Megaventory extension 
									</label></td>
									<td class="value"><select
										id="megaventory_connectivity_enabled-id"
										name="megaventory_enabled">
										<option value="1" <?php if ($enabled == '1') echo ' selected'; ?>>Enabled</option>
										<option value="0" <?php if ($enabled == '0') echo ' selected'; ?>>Disabled</option>
										</select></td>
								</tr>
								<tr id="row_megaventory_connectivity_apiurl">
									<td class="label"><label
										for="megaventory_connectivity_apiurl-id"> API URL
									</label></td>
									<td class="value"><input
										id="megaventory_connectivity_apiurl-id"
										name="megaventory_apiurl"
										value="<?php echo $this->getSettingValue('apiurl'); ?>"
										class=" input-text" type="text"></td>
								</tr>
								<tr id="row_megaventory_connectivity_apikey">
									<td class="label"><label
										for="megaventory_connectivity_apikey-id"> API Key
									</label></td>
									<td class="value"><input
										id="megaventory_connectivity_apikey-id"
										name="megaventory_apikey"
										value="<?php echo $this->getSettingValue('apikey'); ?>"
										class=" input-text" type="text"></td>
								<tr>
									<td>&nbsp;</td>
									<td class="label" colspan="2">
										<button id="save-config-btn" type="button"
											onclick="checkConnectivity()">
											<span>Update</span>
										</button><br/><br/>
										<?php if ($connectivityOk === true) { ?>
											<span id="connectivity-message-id">
                    						Connectivity OK<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/accept.png')?>" style="position:relative;top:1px;left:4px;"/>
											</span>
										<?php } else {?>
											<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/exclamation.png')?>" title="" style="position:relative;top:1px;right:4px;"/>
											<span id="connectivity-message-id">Connectivity Failed.<br/><?php echo $connectivityOk ?>
											</span>
											<span style="color:red;" id="connectivity-error-message-id"></span>
										<?php } ?>
										<br/>
										<?php $soapUserUrl = Mage::helper("adminhtml")->getUrl("adminhtml/api_user"); ?>
										<a id="soap-user-link-id" style="display:none;" href="<?php echo $soapUserUrl ?>">Go to SOAP Users page</a>
									</td>
								</tr>
								<?php if(empty($syncTimestamp)){ ?>
									<tr id="row_megaventory_connectivity_order">
										<td class="label"><label
											for="megaventory_connectivity_order-id"> Order Synchronization
										</label></td>
										<td class="value">
											<input type="checkbox" disabled 
											onclick="checkOrderSynchronization(this.checked, this);"
											<?php if ($orderSyncrhonization === '1') { ?>checked<?php } ?>
											id="megaventory_connectivity_order-id"
											name="megaventory_order_synchronization"/>
											<div>
												This option will be enabled when the Setup Wizard ends successfully. 
												While this option is unchecked, no sales orders are sent to Megaventory from Magento. 
												This option should be enabled only when the inventory quantities of Magento and Megaventory are synchronized 
												(after the Setup Wizard ends succesfully).
											</div>
										</td>
									</tr>
								<?php } else { ?>
									<tr id="row_megaventory_connectivity_order">
										<td class="label"><label
											for="megaventory_connectivity_order-id"> Order Synchronization
										</label></td>
										<td class="value">
											<input type="checkbox"
											onclick="checkOrderSynchronization(this.checked, this);"
											<?php if ($orderSyncrhonization === '1') { ?>checked<?php } ?>
											id="megaventory_connectivity_order-id"
											name="megaventory_order_synchronization"/>
											<div>
												Check this option to enable order synchronization between Magento and Megaventory. 
												While this option is unchecked, no sales orders are sent to Megaventory from Magento. 
												This option should be enabled only when the inventory quantities of Magento and Megaventory are synchronized 
												(after the Setup Wizard ends succesfully).
											</div>
										</td>
									</tr>
								<?php } ?>
							</tbody>
						</table>

					</fieldset>
					<script type="text/javascript">Fieldset.applyCollapse('megaventory_connectivity');</script>
				</div>

			</td>
			<td style="padding-left: 15px">
				<div class="entry-edit" id="setup-wizard-id"
					<?php if (empty($apikey) || empty($apiurl)) { ?>
					style="display: none" <?php }?>>
					<div class="entry-edit-head collapseable">
						<a id="megaventory_synchronize-head" href="#"
							onclick="Fieldset.toggleCollapse('megaventory_synchronize', ''); return false;"
							class="open"> Setup Wizard</a>
					</div>
					<input id="megaventory_synchronize-state" type="hidden" value="1">
					<fieldset class="config collapseable" id="megaventory_synchronize"
						style="">
						<legend>Setup Wizard</legend>
				<?php if(empty($syncTimestamp)){ ?>
					<table class="form-list" style="width:100%">
							<tr>
								<td width="50%" class="label"><label
									for="megaventory_magento_id-id">Magento Id<span class="required">*</span>
								</label></td>
								<td class="value">
									<select id="megaventory_magento_id-id" name="" <?php if ($magentoInstallations <= 0) echo 'disabled'?>>
										<?php 
										for ($i = 0; $i < $magentoInstallations; $i++)
										{
											$value = ($i>0) ? 'magento-'.$i : 'magento';
										?>
										<option value="<?php echo $value ?>" <?php if ($magentoId == $value) echo 'selected' ?>>
											<?php echo 'magento-'.$i ?>
										</option>
										<?php 
										}?>
									</select>
								</td>
							</tr>
							<tr>
								<td width="50%" class="label"><label
									for="megaventory_shipping_sku-id"> Shipping Product SKU<span class="required">*</span>
								</label></td>
								<td class="value"><input
									id="megaventory_shipping_sku-id"
									name="megaventory_shippingproduct"
									value="<?php echo $this->getSettingValue('shippingproductsku'); ?>"
									class=" input-text" type="text">
									<div style="display:none" class="validation-advice" id="megaventory_shipping_sku-id-required" style="">This is a required field.</div>
									</td>
							</tr>
							<tr>
								<td class="label"><label
									for="megaventory_discount_sku-id"> Discount Product SKU<span class="required">*</span>
								</label></td>
								<td class="value"><input
									id="megaventory_discount_sku-id"
									name="megaventory_discountproduct"
									value="<?php echo $this->getSettingValue('discountproductsku'); ?>"
									class=" input-text" type="text">
									<div style="display:none" class="validation-advice" id="megaventory_discount_sku-id-required" style="">This is a required field.</div>
									</td>
							</tr>
							<tr>
								<td class="label" colspan="2">
								<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/message.png')?>" style="position:relative;top:1px;left:4px;margin-right:10px;"/>
								<span style="font-weight:bold;">If you are using any custom attribute for Supplier Management in Magento <br/>please fill in the field below the 
								<font style="color:rgb(187, 32, 32)">attribute code</font> of this attribute (i.e supplier, manufacturer etc). 
								<br/>Only attributes of frontend type Text or Dropdown are supported.
								<br/>The field is not mandatory.</span>
								</td>
							</tr>
							<tr>
								<td class="label"><label
									for="megaventory_supplier-id">Supplier Attribute Code
									</label></td>
								<td class="value"><input
									id="megaventory_supplier-id"
									name="supplier_attribute_code"
									value="<?php echo $this->getSettingValue('supplierattributecode'); ?>"
									class=" input-text" type="text">&nbsp;
										<?php if(!empty($syncTimestamp)){ ?>
										<button id="save-config-btn" type="button"
											onclick="updateSupplierSettings()">
											<span>Update</span>
										</button>
										<?php } ?>
									</td>
							</tr>
							<tr>
								<td colspan="2" style="width: 500px;"><strong>Initialize Data</strong></td>
								
							</tr>
							<tr>
								<td colspan="2">
									<div id="sync-data-id">
										<span id="sync-heading-id"></span>
										<ul id="sync-data-progress-id">

										</ul>
									</div>
								</td>
							</tr>
							<tr>
								<td class="label" colspan="2">
									<?php if ($connectivityOk === true) { 
										if ($this->checkBaseCurrencies())
										{
										?>
									<button id="sync-data-btn" type="button"
										onclick="javascript:syncData()" <?php if (empty($apikey) || empty($apiurl)) { ?> style="display: none;" <?php }?>>
										<span> Start </span>
									</button>
									<?php } else {?> 
									<span id="currencies-message-id">
									<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/exclamation.png')?>" 
									style="position:relative;top:1px;"/>
									<br/>Setup Wizard cannot start. 
									<br/>You must set your Magento and Megaventory default Currencies to the same value.
									<br/>Current default values are <?php echo $this->getDefaultMagentoCurrency() ?> for Magento and <?php echo $this->getDefaultMegaventoryCurrency() ?> for Megaventory.
									<br/>Please contact <a href="http://megaventory.com/?contact-us=1" target="_blank">Megaventory Support</a>    
									</span>	
										  <?php }
									} else {
									?>
									<span id="connectivity-message-id">Connection Failed
									<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/exclamation.png')?>" title="<?php echo $connectivityOk ?>" style="position:relative;top:1px;left:4px;"/></span>
									<span style="color:red;" id="connectivity-error-message-id"></span>
									<?php }?>
									<div id="next-step" style="display:none;">
										<br/>
										<strong>Please select the Inventory Location you want to import your global stock to</strong>&nbsp;&nbsp;
										<select
											name="initial-stock-inventory" id="initial-stock-inventory-id">
											<?php foreach ($this->getInventories() as $inventory):?>
											<option value="<?php echo $inventory->getId()?>">
												<?php echo $inventory->getName()?>
											</option>
											<?php endforeach;?>
										</select>
										<br />
										<br />
											<button id="export-stock-btn" type="button" style="margin-left:auto;margin-right:auto;display:table"
												onclick="exportStockAndFinish()">
												<span> Export Magento Stock in Megaventory compatible csv file</span>
											</button>&nbsp;
											<button id="" type="button"  style="margin-left:auto;margin-right:auto;display:table"
												onclick="location = '<?php echo $indexURL ?>';">
												<span> Cancel, I will import Megaventory stock manually </span>
											</button>
											<br />
										<br /> <span id="export-stock-csv"></span>
										<br><br>
										<button id="finish-btn" type="button" style="display:none;"
											onclick="javascript:location = '<?php echo $indexURL ?>';">
											<span> Finish </span>
										</button>	
										<!-- 
										<br>
										Do you want to import your Magento stock to Megaventory?<br>
										<button id="next1-data-yes-btn" type="button"
											onclick="javascript:next1Setup()">
											<span> Yes </span>
										</button>&nbsp;
										<button id="next1-data-no-btn" type="button"
											onclick="javascript:location = '<?php echo $indexURL ?>';">
											<span> No </span>
										</button>
										-->
									</div>
									<div id="next-error" style="display:none;">
										<br>
										<button id="error1-data-no-btn" type="button"
											onclick="javascript:location = '<?php echo $indexURL ?>';">
											<span> Refresh Page </span>
										</button>
									</div>
									<button id="reset-data-btn" type="button"
										onclick="javascript:resetSetup()" style="display: none;">
										<span> Reset Setup </span>
									</button>
								</td>
							</tr>
							<!--tr>
								<td id="stock-setup-id" class="stock-setup" colspan="2"
									style="display: none;padding-top:10px;">
									<strong>Please select the Inventory Location you want to import your global stock to</strong><br /> 
									<select
									name="initial-stock-inventory" id="initial-stock-inventory-id">
										<?php foreach ($this->getInventories() as $inventory):?>
										<option value="<?php echo $inventory->getId()?>">
											<?php echo $inventory->getName()?>
										</option>
										<?php endforeach;?>
									</select><br />
								<br />
									<button id="export-stock-btn" type="button"
										onclick="exportStock()">
										<span> Export Initial Stock csv </span>
									</button>&nbsp;
									<button id="" type="button"
										onclick="location = '<?php echo $indexURL ?>';">
										<span> Cancel </span>
									</button>
									<br />
								<br /> <span id="export-stock-csv"></span>	
								</td>
							</tr-->
						</table>
					<?php } else {?>
					<table class="form-list" style="width:100%">
							<tr>
								<td width="50%" class="label"><label
									for="megaventory_magento_id-id">Magento Id<span class="required">*</span>
								</label></td>
								<td class="value">
									<select id="megaventory_magento_id-id" name="" <?php if ($magentoInstallations <= 0) echo 'disabled'?>>
									<?php 
									for ($i = 0; $i < $magentoInstallations; $i++)
									{
										$value = ($i>0) ? 'magento-'.$i : 'magento';
									?>
									<option value="<?php echo $value ?>" <?php if ($magentoId == $value) echo 'selected' ?>>
										<?php echo 'magento-'.$i ?>
									</option>
									<?php 
									}?>
								</select>
								<?php if(!empty($syncTimestamp) && $connectivityOk === true){ ?>
									<button id="save-config-btn" type="button"
										onclick="updateMagentoId()">
										<span>Update</span>
									</button>
								<?php } ?>
								</td>
							</tr>
							<tr>
								<td class="label"><label
									for="megaventory_shipping_sku-id"> Shipping Product SKU<span class="required">*</span>
								</label></td>
								<td class="value"><input
									id="megaventory_shipping_sku-id" disabled 
									name="megaventory_shippingproduct"
									value="<?php echo $this->getSettingValue('shippingproductsku'); ?>"
									class=" input-text disabled" type="text">
									<div style="display:none" class="validation-advice" id="megaventory_shipping_sku-id-required" style="">This is a required field.</div>
									</td>
							</tr>
							<tr>
								<td class="label"><label
									for="megaventory_discount_sku-id"> Discount Product SKU<span class="required">*</span>
								</label></td>
								<td class="value"><input
									id="megaventory_discount_sku-id" disabled
									name="megaventory_discountproduct"
									value="<?php echo $this->getSettingValue('discountproductsku'); ?>"
									class=" input-text disabled" type="text">
									<div style="display:none" class="validation-advice" id="megaventory_discount_sku-id-required" style="">This is a required field.</div>
									</td>
							</tr>
							<tr>
								<td class="label" colspan="2">
								<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/message.png')?>" style="position:relative;top:1px;left:4px;margin-right:10px;"/>
								<span style="font-weight:bold;">If you are using any custom attribute for supplier management in Magento <br/>please fill in the field below the 
								<font style="color:rgb(187, 32, 32)">attribute code</font> of this attribute (i.e supplier, manufacturer etc).
								<br/>Only attributes of frontend type Text or Dropdown are supported.
								<br/>The field is not mandatory.</span>
								</td>
							</tr>
							<tr>
								<td class="label"><label
									for="megaventory_supplier-id">Supplier Attribute Code
									</label></td>
								<td class="value"><input
									id="megaventory_supplier-id"
									name="supplier_attribute_code"
									value="<?php echo $this->getSettingValue('supplierattributecode'); ?>"
									class=" input-text" type="text">&nbsp;
										<?php if(!empty($syncTimestamp)){ ?>
										<button id="save-config-btn" type="button"
											onclick="updateSupplierSettings()">
											<span>Update</span>
										</button>
										<?php } ?>
									</td>
							</tr>
							<tr id="row_megaventory_general_shippingproductsku">
								<td colspan="2"><strong>Setup Report</strong><br />
							<?php echo $this->getSettingValue('syncreport'); ?>
							</td>
							</tr>
							<tr>
								<td colspan="2" class="label">
									<button id="sync-data-btn" type="button"
										onclick="javascript:resetSetup()">
										<span> Reset Setup </span>
									</button>
								</td>
							</tr>
						</table>	
				<?php }?>
    	</fieldset>
					<script type="text/javascript">Fieldset.applyCollapse('megaventory_synchronize');</script>
				</div>

			</td>
		</tr>
<?php if (!empty($syncTimestamp)) {?>
		<tr>
			<td colspan="2">
				<div class="entry-edit">
					<div class="entry-edit-head collapseable">
						<a id="megaventory_inventories-head" href="#"
							onclick="Fieldset.toggleCollapse('megaventory_inventories', ''); return false;"
							class="open">Inventory Locations</a>
					</div>
					<input id="megaventory_inventories-state" type="hidden" value="1">
					<fieldset class="config collapseable" id="megaventory_inventories"
						style="">
						<legend>Inventory Locations</legend>
						<div class="grid">
							<div class="hor-scroll">
								<?php 
								
								$updateIvnentoryLocationsUrl = Mage::helper("adminhtml")->getUrl("megaventory/index/updateInventoryLocations");
								if ($connectivityOk === true) { ?>
									<button title="Update Inventory Locations Data" type="button"
										onclick="setLocation('<?php echo $updateIvnentoryLocationsUrl ?>')"
										style="margin:5px;">
										<span>Update Inventory Locations Data</span>
									</button>
									<?php } else { ?>
									<button class="disabled" type="button" title="No connectivity"
										onclick=""
										style="margin:5px;">
										<span>Update Inventory Locations Data</span>
									</button>
								<?php } ?>
								<table cellspacing="0" class="data"
									id="mv_megaventory_inventories_grid_table">
									<colgroup>
										<col width="50">
										<col>
										<col>
										<col>
										<col>
										<col>
									</colgroup>
									<thead>
										<tr class="headings">
											<th><span class="nobr">ID</span></th>
											<th><span class="nobr">Short Name</span></th>
											<th><span class="nobr">Name</span></th>
											<th width="30%"><span class="nobr">Address</span></th>
											<th class=" no-link"><span class="nobr">Visible - Counts in global stock</span></th>
											<th class=" no-link last"><span class="nobr">Default</span></th>
										</tr>
									</thead>

									<tbody>
										<?php 
										$i = 0;
										$checkCountsInStock = Mage::helper("adminhtml")->getUrl("megaventory/index/updateCountsInStock");
										$syncIvnentoriesUrl = Mage::helper("adminhtml")->getUrl("megaventory/index/importInventories");
										
										foreach ($this->getInventories() as $inventory):
										$makeDefaultUrl = Mage::helper("adminhtml")->getUrl('*/*/makeDefaultInventory', array('id' => $inventory->getId()));
										?>
										<tr title="" class="<?php if ($i%2 == 1) echo 'even'; ?>"><td class="a-right "><?php echo $inventory->getId()?></td>
											<td class=""><?php echo $inventory->getShortname()?>&nbsp;</td>
											<td class=""><?php echo $inventory->getName()?>&nbsp;</td>
											<td class=""><?php echo $inventory->getAddress()?>&nbsp;</td>
											<td class="a-center ">
											<?php if (!$inventory->getIsdefault()){?>
											<input type="checkbox" <?php if ($inventory['counts_in_total_stock'] == 1) {?>checked<?php }?> <?php echo $actionsDisabled ?>
												<?php if ($connectivityOk === true) { ?>onclick="changeCountsInStock('<?php echo $inventory->getId() ?>', this.checked ,'<?php echo $checkCountsInStock?>',this)"<?php } ?>/>
											<?php } else { ?>
											<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/accept.png')?>"/>
											<?php } ?>
											</td>
											<td class=" last">
											<?php if ($inventory->getIsdefault() == 1){?>
											Yes
											<?php } else if ($inventory['counts_in_total_stock'] == 1) {
												?>
												<a
												href="<?php echo $makeDefaultUrl?>">Make
													Default</a>
											<?php }?>
											</td>
										</tr>
										<?php 
										$i++;
										endforeach;
										//if ($i%2 == 1) $trClass = 'even';
										?>
									</tbody>
								</table>
									<br/>
									<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/message.png')?>" style="position:relative;top:1px;left:4px;margin-right:10px;"/>
									<span>Your Magento orders are always sent to the default Inventory Location</span>									
									<br/><br>
									<?php if ($connectivityOk === true) {?>
										<button id="id_a7ba1155132fd25062ba7095d6836def" type="button"
											onclick="confirmSetLocation('This action will recalculate global magento quantities based on the quantities of the selected inventory locations of your megaventory account. Proceed only if you understand this warning.','<?php echo $syncIvnentoriesUrl ?>')" 
											style="">
											<span>Import Inventory from Megaventory</span>
										</button>
										<br/><br/>
										<strong>-OR-</strong><br><br>
										<button id="export-stock-btn" type="button"
											onclick="exportStock()">
											<span>Export Magento Stock for Inventory Location:</span>
										</button>&nbsp;&nbsp;
										<select name="initial-stock-inventory"
										id="initial-stock-inventory-id">
											<?php foreach ($this->getInventories() as $inventory):?>
											<option value="<?php echo $inventory->getId()?>">
												<?php echo $inventory->getName()?>
											</option>
											<?php endforeach;?>
											</select>
											&nbsp;&nbsp;
									 	<span id="export-stock-csv"></span>
									 <?php } else { ?>
									 	<button id="id_a7ba1155132fd25062ba7095d6836def" type="button" title="No connectivity"
											onclick="" class="disabled"
											style="">
											<span>Import Inventory from Megaventory</span>
										</button>
										<br/><br/>
										<strong>-OR-</strong><br><br>
										<button id="export-stock-btn" type="button" title="No connectivity"
											onclick="" class="disabled">
											<span>Export Magento Stock for Inventory Location:</span>
										</button>&nbsp;&nbsp;
										<select name="initial-stock-inventory"
										id="initial-stock-inventory-id">
											<?php foreach ($this->getInventories() as $inventory):?>
											<option value="<?php echo $inventory->getId()?>">
												<?php echo $inventory->getName()?>
											</option>
											<?php endforeach;?>
											</select>
											&nbsp;&nbsp;
									 	<span id="export-stock-csv"></span>
									 
									 <?php } ?>
							</div>
						</div>
					</fieldset>
					<script type="text/javascript">Fieldset.applyCollapse('megaventory_inventories');</script>
				</div>
			</td>
			<!--td style="padding-left: 15px">
				<div class="entry-edit">
					<div class="entry-edit-head collapseable">
						<a id="megaventory_suppliers-head" href="#"
							onclick="Fieldset.toggleCollapse('megaventory_suppliers', ''); return false;"
							class="open">Suppliers</a>
					</div>
					<input id="megaventory_suppliers-state" type="hidden" value="1">
					<fieldset class="config collapseable" id="megaventory_suppliers"
						style="">
						<legend>Suppliers</legend>
					<table class="form-list" style="width:100%">
						<tr>
							<td width="50%" class="label"><label
								for="megaventory_supplier-id">Supplier Attribute Code
							</label></td>
							<td class="value"><input
								id="megaventory_supplier-id"
								name="supplier_attribute_code"
								value="<?php echo $this->getSettingValue('supplierattributecode'); ?>"
								class=" input-text" type="text">
								</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td class="label" colspan="2">
								<button id="save-config-btn" type="button"
									onclick="updateSupplierSettings()">
									<span>Update</span>
								</button>
							</td>
						</tr>
					</table>
					</fieldset>
					<script type="text/javascript">Fieldset.applyCollapse('megaventory_suppliers');</script>
				</div>
			</td-->
		</tr>
		<tr>
			<td colspan="2">
				<div class="entry-edit">
					<div class="entry-edit-head collapseable">
						<a id="megaventory_taxes-head" href="#"
							onclick="Fieldset.toggleCollapse('megaventory_taxes', ''); return false;"
							class="open">Taxes</a>
					</div>
					<input id="megaventory_taxes-state" type="hidden" value="1">
					<fieldset class="config collapseable" id="megaventory_taxes"
						style="">
						<legend>Taxes</legend>
						<div class="grid">
							<div class="hor-scroll">
								<table cellspacing="0" class="data"
									id="mv_megaventory_taxes_grid_table">
									<colgroup>
										<col width="50">
										<col>
										<col>
										<col>
										<col>
										<col>
									</colgroup>
									<thead>
										<tr class="headings">
											<th><span class="nobr">ID</span></th>
											<th><span class="nobr">Name</span></th>
											<th><span class="nobr">Description</span></th>
											<th><span class="nobr">Percentage</span></th>
										</tr>
									</thead>

									<tbody>
										<?php 
										$i = 0;
										$syncTaxessUrl = Mage::helper("adminhtml")->getUrl("megaventory/index/synchronizeTaxes");
										foreach ($this->getTaxes() as $tax):
										?>
										<tr title="" class="<?php if ($i%2 == 1) echo 'even'; ?>"><td class="a-right "><?php echo $tax->getId()?></td>
											<td class=" "><?php echo $tax->getName()?>&nbsp;</td>
											<td class=" "><?php echo $tax->getDescription()?>&nbsp;</td>
											<td class=" "><?php echo $tax->getPercentage()?>&nbsp;</td>
										</tr>
										<?php 
										$i++;
										endforeach;?>
									</tbody>
								</table><br/>
									<?php if ($connectivityOk === true) {?>
										<button id="sync-taxes-id" title="Synchronize Taxes" type="button"
											onclick="setLocation('<?php echo $syncTaxessUrl ?>')" 
											style="">
											<span>Synchronize Taxes</span>
										</button>
									<?php } else { ?>
										<button id="sync-taxes-id" title="No connectivity" type="button"
											onclick="" 
											style="" class="disabled">
											<span>Synchronize Taxes</span>
										</button>
									<?php } ?>
							</div>
						</div>
					</fieldset>
					<script type="text/javascript">Fieldset.applyCollapse('megaventory_taxes');</script>
				</div>
			</td>
		</tr>
<?php } ?>
		<tr>
			<td colspan="2">
				<div class="entry-edit">
					<div class="entry-edit-head collapseable">
						<a id="megaventory_manual-head" href="#"
							onclick="Fieldset.toggleCollapse('megaventory_manual', ''); return false;"
							class="open">User Manuals</a>
					</div>
					<input id="megaventory_manual-state" type="hidden" value="1">
					<fieldset class="config collapseable" id="megaventory_manual"
						style="">
						<legend>User Manuals</legend>
						<div class="grid">
							<div>
								<a href="http://www.megaventory.com/Megaventory_Manual.pdf" target="_blank">Megaventory  Manual<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/pdf.png')?>" style=" position: relative; top: 25px;"/></a><br/>
								<a href="https://www.megaventory.com/Megaventory-Magento-Integration-Instructions.pdf" target="_blank">Megaventory - Magento Integration Manual<img src="<?php echo Mage::getDesign()->getSkinUrl('images/megaventory/pdf.png')?>" style=" position: relative; top: 25px;"/></a>
							</div>
						</div>
					</fieldset>
					<script type="text/javascript">Fieldset.applyCollapse('megaventory_manual');</script>
				</div>
			</td>
		</tr>
	</table>
</form>
<script>

function checkConnectivity(){
	url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/checkConnectivity") ?>";
	new Ajax.Request(url, {
		parameters:  
			{
				'megaventory_apiurl' : $('megaventory_connectivity_apiurl-id').value,
				'megaventory_apikey' : $('megaventory_connectivity_apikey-id').value,
				'megaventory_enabled' : $('megaventory_connectivity_enabled-id')[$('megaventory_connectivity_enabled-id').selectedIndex].value
			},
        onSuccess: function(transport) {
        	location = '<?php echo $indexURL ?>';
        }
    });
}

function syncData()
{
	$('megaventory_shipping_sku-id-required').hide();
	$('megaventory_discount_sku-id-required').hide();
	
	flag = 0;
	if ($('megaventory_shipping_sku-id').value.trim() == ''){
		$('megaventory_shipping_sku-id-required').show();
		flag = 1;
	}
	if ($('megaventory_discount_sku-id').value.trim() == ''){
		$('megaventory_discount_sku-id-required').show();
		flag = 1;
	}

	if (flag)
		return;

	$('megaventory_shipping_sku-id').addClassName('disabled');
	$('megaventory_discount_sku-id').addClassName('disabled');
	$('megaventory_shipping_sku-id').disable();
	$('megaventory_discount_sku-id').disable();
	
	var updateSKUs = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/setShippingAndDiscountSKUs") ?>";
	var ajax = new Ajax.Request(updateSKUs, {
        parameters: {
            shippingSKU: $('megaventory_shipping_sku-id').value, 
            discountSKU: $('megaventory_discount_sku-id').value,
            magentoId: $('megaventory_magento_id-id').value,
            magento_supplier_code: $('megaventory_supplier-id').value
        },
        onSuccess: function(transport) {
        	var result = transport.responseText.evalJSON();
        	var html = result.message;
        	if (html){
        		alert(html);
        		location = '<?php echo $indexURL ?>'; 
        	}
        	else
        	{
				continueSyncData();
        	}
        }
    });

}

function continueSyncData()
{
	
	$('sync-heading-id').update('Initialization process started.Please do not close browser window while initialization runs');
    $('sync-data-btn').hide();
    
    
    sync('inventories','1',0);
   
	executer = new PeriodicalExecuter(
    		function(pe)
    		{
    			var url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/getProgress") ?>";
    			new Ajax.Request(url, {
    		        method:'get',
    		        onSuccess: function(transport) {
    		        	var result = transport.responseText.evalJSON();
    		            	var html = result.message;
    		            	$('sync-data-progress-id').update(html);

    		            if (result.step == 'done'){
       		            	pe.stop();
       		            	$('megaventory_connectivity_order-id').disabled = false;
    		            }
    		        }
    		    });
    		},1);
}

function sync(step,page,imported)
{
	var url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/syncData") ?>";

    var ajax = new Ajax.Request(url, {
        method:'get',
        parameters: {step: step, page: page, imported: imported},
        onSuccess: function(transport) {
        	var result = transport.responseText.evalJSON();
        	if (result.nextstep != 'finish' && result.nextstep != 'finisherror'){
            	sync(result.nextstep,result.nextpage,result.imported);
        	}
        	else{
	            executer.stop();
	            if (result.nextstep != 'finisherror'){
	            	next1Setup();
	            	//$('next-step').show();
	            }
	            else
	            	$('next-error').show();
        	}
        }
    });
}


function resetSetup()
{
	var r=confirm("Reseting Setup will delete all Megaventory data from your Magento installation.Are you sure you want to proceed?");
	if (r==true)
	{
		url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/resetSetup") ?>";
		new Ajax.Request(url, {
			
	        onSuccess: function(transport) {
	            alert('Setup was reset');
	            location = '<?php echo $indexURL ?>';
	        }
	    });
	}
}

function confirmSetLocation(message,location)
{
	var r=confirm(message);
	if (r==true)
	{
		setLocation(location);
	}
}

function next1Setup()
{
     	url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/getInventories") ?>";
		new Ajax.Request(url, {
	        onSuccess: function(transport) {
	        	//$('stock-setup-id').show();
	        	var response = transport.responseText.evalJSON();
	        	//add inventories to select object
				$('initial-stock-inventory-id').update(response.options);
				$('next-step').show();
	        }
	    });
}

function exportStock()
{
	url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/exportStock") ?>";

	new Ajax.Request(url, {
		parameters:  
		{
			'inventory' : $('initial-stock-inventory-id').options[$('initial-stock-inventory-id').selectedIndex].value,
		},
        onSuccess: function(transport) {
            var link = '<a href="/var/export/InitialQuantities.csv">Download InitialQuantities File</a>';
        	$('export-stock-csv').update(link);
        }
    });
}


function exportStockAndFinish()
{
	url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/exportStock") ?>";

	new Ajax.Request(url, {
		parameters:  
		{
			'inventory' : $('initial-stock-inventory-id').options[$('initial-stock-inventory-id').selectedIndex].value,
		},
        onSuccess: function(transport) {
            var link = '<a href="/var/export/InitialQuantities.csv">Download InitialQuantities File</a>';
        	$('export-stock-csv').update(link);
        	$('finish-btn').show();
        }
    });
}

function changeCountsInStock(inventoryId , oneOrZero, url, checkBox){

	var r=confirm('You are about to change the Inventory Locations that contribute to the global stock of Magento. If you proceed, you should also click "Import Inventory from Megaventory" to synchronize quantities before leaving the page.');
	if (r==true)
	{
	    new Ajax.Request(url, {
	
	        method:'post',
	
	        parameters : {
	
	            inventoryId:inventoryId,
	
	            value:oneOrZero
	
	        },
	
	        onFailure: function() {
	
	            alert('An error occurred while saving the data.');
	
	        },
	
	        onSuccess : function(response){
				location = '<?php echo $indexURL ?>';
	        }
	
	    });
	}
	else
	{
		checkBox.checked = !checkBox.checked;
	}
}

function checkOrderSynchronization(oneOrZero, checkBox){

	<?php $updateOrderSynchronization = Mage::helper("adminhtml")->getUrl("megaventory/index/updateOrderSynchronization"); ?>
	var r=confirm('You are about to change the Order Synchronization status. Are you sure you want to proceed?');
	if (r==true)
	{
	    new Ajax.Request('<?php echo $updateOrderSynchronization ?>', {
	
	        method:'post',
	
	        parameters : {
	
	            value:oneOrZero
	
	        },
	
	        onFailure: function() {
	
	            alert('An error occurred while saving the data.');
	
	        },
	
	        onSuccess : function(response){
				
	        }
	
	    });
	}
	else
	{
		checkBox.checked = !checkBox.checked;
	}
}

function updateSupplierSettings(){
	url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/updateSupplierSettings") ?>";
	new Ajax.Request(url, {
		parameters:  
			{
				'magento_supplier_code' : $('megaventory_supplier-id').value
			},
        onSuccess: function(transport) {
            if (transport.responseText){
	        	var result = transport.responseText.evalJSON();
	        	
	        	alert(result.message);
            }
        	location = '<?php echo $indexURL ?>';
        }
    });
}

function updateMagentoId(){
	url = "<?php echo Mage::helper("adminhtml")->getUrl("megaventory/index/updateMagentoId") ?>";
	new Ajax.Request(url, {
		parameters:  
			{
				'magento_id' : $('megaventory_magento_id-id').value
			},
        onSuccess: function(transport) {
            if (transport.responseText){
	        	var result = transport.responseText.evalJSON();
	        	
	        	alert(result.message);
            }
        }
    });
}

</script>